### ISSUE TITLE
Original air date

### ISSUE THREAD

**Issue by nbousfield** [dougwaldron/podcast-rewind#73]
Hi, enjoying the service so far.

I think it would be nice to add the original posting date in the show-notes, if possible.

Thanks!

**Comment by dougwaldron** [comment]
Hey, glad you're enjoying it! And thanks for the suggestion. It's actually already supposed to do this, but it's not working with some podcast feeds. I'll try to track down the problem.

Here's what it's supposed to look like when it works:
![podcast-original-date-example](https://github.com/dougwaldron/podcast-rewind/assets/737326/a8f6bfb8-2d35-44a9-aed4-1be148e2495d)

**Comment by dougwaldron** [comment]
There are (at least) three RSS elements that might be displayed as show notes in a podcast app. If more than one is present, Overcast will display only one in this order of preference: `<content:encoded>`, `<description>`, `<itunes:summary>`. Other podcast apps may differ.

Currently, only `<description>` is getting updated with the original publication date.

**Comment by nbousfield** [comment]
Hi Doug, sorry for the delay in getting back to you.

That original air date now shows for the podcast, which is great! I added
another podcast (Cortex on Relay FM) and it seems like the shownotes in the
original RSS feed are being swapped with one of the others that you
mentioned. Not a big deal to me since I open them in a web browser anyways,
but wanted to let you know in case it's an easy fix.

Appreciate the service!

**Comment by dougwaldron** [comment]
Hey @nbousfield, I'm not sure what you mean, could you share an example of what you're seeing or a screenshot maybe? Thanks.
